version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3
    working_directory: ~/vim-jp
    environment:
      - JEKYLL_ENV=production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      - JOB_RESULTS_PATH=run-results
    steps:
      - checkout
      - restore_cache:
          key: vim-jp-{{ .Branch }}-{{ checksum "Gemfile" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: vim-jp-{{ .Branch }}-{{ checksum "Gemfile" }}
          paths:
            - "vendor/bundle"
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build -d jekyll/_site/docs/
      - store_artifacts:
          path: jekyll/_site/docs/
          destination: vim-jp
